ImportXmlToJson/Models/Contract.cs
using System.ComponentModel.DataAnnotations;

namespace ImportXmlToJson.Models
{
    public class Contract
    {
        public int? Id { get; set; }

        [Required]
        [Display(Name ="Шифр договора")]
        public int? Shifr_Contract { get; set; }

        [Required]
        [Display(Name ="Наименование договора")]
        public string Name_Contract { get; set;}

        [Required]
        [Display(Name ="Заказчик")]
        public string Seller { get; set; }
    }
}

ImportXmlToJson/Models/ErrorViewModel.cs
namespace ImportXmlToJson.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ImportXmlToJson/Models/Imports.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ImportXmlToJson.Models
{
    [Table("StageContract")]
    public class Imports
    {
        public int? Id { get; set; }

        [Display(Name="Наименование Этапа")]
        public string Contract_Stage { get; set; }

        [Display(Name="Дата начала")]
        [DataType(DataType.Date)]
        public DateTime StartDate { get; set; }

        [Display(Name ="Дата окончания")]
        [DataType(DataType.Date)]
        public DateTime EndDate { get; set; }
    }
}

ImportXmlToJson/Controllers/ContractsController.cs
using ImportXmlToJson.Domain;
using ImportXmlToJson.Models;
using OfficeOpenXml;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ImportXmlToJson.Data;
using Microsoft.AspNetCore.Mvc.Filters;

namespace ImportXmlToJson.Controllers
{
    public class ContractsController : Controller
    {
        private readonly ContractsRepository contractsRepository;

        public ContractsController(ContractsRepository contractsRepository)
        {
            this.contractsRepository = contractsRepository;
        }

        public IActionResult Index()
        {
            var model = contractsRepository.GetContract();
            return View(model);
        }
        public IActionResult ContractEdit(int? id)
        {
            Contract model = id == null ? new Contract() : contractsRepository.GetContractById(id);
            return View(model);
        }

        [HttpPost]
        public IActionResult ContractEdit(Contract model)
        {
            if (ModelState.IsValid)
            {
                contractsRepository.SaveContract(model);
                return RedirectToAction("Index");
            }

            return View(model);
        }

        [HttpPost]
        public IActionResult ContractDelete(int? id)
        {
            contractsRepository.DeleteContract(new Contract() { Id = id });
            return RedirectToAction("Index");
        }

        public async Task<List<Contract>> ImportExcel(IFormFile file)
        {
            var list = new List<Contract>();
            using (var stream = new MemoryStream())
            {
                if (file == null)
                {
                    return list;
                }
                await file.CopyToAsync(stream);
                using (var packeg = new ExcelPackage(stream))
                {
                    ExcelWorksheet worksheet = packeg.Workbook.Worksheets[0];
                    var rowcount = worksheet.Dimension.Rows;
                    for (int row = 1; row <= rowcount ; row++)
                    {
                        list.Add(new Contract(){
                            Shifr_Contract = Convert.ToInt32(worksheet.Cells[row, 1].Value.ToString().Trim()),
                            Name_Contract = worksheet.Cells[row, 2].Value.ToString().Trim(),
                            Seller = worksheet.Cells[row, 3].Value.ToString().Trim()
                        });
                    }
                }
            }
            foreach (var item in list)
            {
                contractsRepository.SaveContract(item);
            }
            return list;
        }

        public IActionResult Imports()
        {
            return View();
        }
    }
}

ImportXmlToJson/Controllers/ImportsController.cs
using Microsoft.AspNetCore.Mvc;
using ImportXmlToJson.Models;
using ImportXmlToJson.Domain;
using System.Text.Json;

namespace ImportXmlToJson.Controllers
{
    public class ImportsController : Controller
    {
        private readonly ImportsRepository importsRepository;

        public ImportsController(ImportsRepository importsRepository)
        {
            this.importsRepository = importsRepository;
        }

        public IActionResult Index()
        {
            var model = importsRepository.GetImports();
            return View(model);
        }

        public IActionResult ImportEdit(int? id)
        {
            Imports model = id == null ? new Imports() : importsRepository.GetImportsById(id);
            return View(model);
        }     
        [HttpPost]
        public IActionResult ImportsEdit(Imports model)
        {
            if (ModelState.IsValid)
            {
                importsRepository.SaveImports(model);
                return RedirectToAction("Index");
            }

            return View(model);
        }

        public IActionResult JsonSerialization(Imports model)
        {
            var dataBase = importsRepository.GetImports();
            var json = JsonSerializer.Serialize(dataBase);
            return Ok(json);
        }

        [HttpPost]
        public IActionResult JsonSerializationByStage(string stage)
        {
            Imports model = stage == null ? new Imports() : importsRepository.GetImportsByStage(stage);
            var json = JsonSerializer.Serialize(model);
            return Ok(json);
        }
    }
}

ImportXmlToJson/Views/Contracts/ContractEdit.cshtml
@using ImportXmlToJson.Domain;
@model ImportXmlToJson.Models.Contract

<div class="text-center">

    <h1>Работа с записью</h1>

    <div>
        <form asp-controller="Contracts" asp-action="ContractEdit" method="post">
            <input type="hidden" asp-for="Id" />
            <div asp-validation-summary="All"></div>

                <label asp-for="Shifr_Contract"></label>
            <div>
                <input asp-for="Shifr_Contract" style="margin-bottom: 20px"  />
                <span asp-validation-for="Shifr_Contract"></span>
            </div>

                <label asp-for="Name_Contract"></label>
            <div>                
                <input asp-for="Name_Contract" style="margin-bottom: 20px" />
                <span asp-validation-for="Name_Contract"></span>
            </div>

                <label asp-for="Seller"></label>
            <div>
                <input asp-for="Seller" ></input>
                <span asp-validation-for="Seller"></span>
            </div>
            <input type="submit" value="Готово" class="btn btn-success" style="height: 50px; width: 200px; margin-top: 20px" />
        </form>
    </div>
</div>

ImportXmlToJson/Views/Contracts/Index.cshtml
@using ImportXmlToJson.Domain;
@model IEnumerable<ImportXmlToJson.Models.Contract>

@{
    ViewData["Title"] = "Title";
}

<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script type="text/javascript" src="https://unpkg.com/xlsx@0.15.1/dist/xlsx.full.min.js"></script>

    
</head>

<body>
    <h1>Загрузка данных</h1>
    <p>
        <a asp-action="ContractEdit" asp-controller="Contracts">Добавить новую запись</a>
    </p>

    <h5>Введите путь к EXCEL файлу на нажмите кнопку "Загрузить".</h5>


    <form method="post" asp-controller="Contracts" asp-action="ImportExcel" enctype="multipart/form-data">
        <input type="file" id="excel_file" name="file" />
        <div id="excel_data" class="mt-5"></div>
        <button type="submit" class="btn btn-outline-warning">Загрузить</button>
    </form>

    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Shifr_Contract)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name_Contract)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Seller)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            
    @foreach (Contract entity in Model) {
            <tr>
                    <th style="padding-top: 30px">
                            @entity.Shifr_Contract  

                    </th>
                    <th style="padding-top: 30px">
                            @entity.Name_Contract   

                    </th>
                    <th style="padding-top: 30px">
                            @entity.Seller  
                    </th>
                    <th>
                    <a asp-action="ContractEdit" asp-route-id="@entity.Id">Редактировать</a>
                    <form method="post" asp-controller="Contracts" asp-action="ContractDelete" >
                            <input type="hidden" value="@entity.Id" name="Id" />
                            <input type="submit" value="Удалить" style="height: 40px; width: 80px" class="btn btn-danger" />
                     </form>
                    </th>
            </tr>                
                }
        </tbody>
    </table>
</body>

<script>

    const excel_file = document.getElementById('excel_file');

    excel_file.addEventListener('change', (event) => {

        var reader = new FileReader();

        reader.readAsArrayBuffer(event.target.files[0]);
        reader.onload = function (event) {
            var data = new Uint8Array(reader.result);

            var work_book = XLSX.read(data, { type: 'array' });

            var sheet_name = work_book.SheetNames;

            var sheet_data = XLSX.utils.sheet_to_json(work_book.Sheets[sheet_name[0]], { header: 1 });

            if (sheet_data.length > 0) {
               var table_output = '<table class="table table-striped table-bordered">';

                for (var row = 0; row < sheet_data.length; row++) {

                    table_output += '<tr>';

                    for (var cell = 0; cell < sheet_data[row].length; cell++) {

                        if (row == 0) {

                            table_output += '<th>' + sheet_data[row][cell] + '</th>';

                        }
                        else {

                            table_output += '<td>' + sheet_data[row][cell] + '</td>';

                        }

                    }

                    table_output += '</tr>';

                }

                table_output += '</table>';

                document.getElementById('excel_data').innerHTML = table_output;
            }

        }
    });
</script>

ImportXmlToJson/Views/Imports/Index.cshtml
@using ImportXmlToJson.Domain;
@model IEnumerable<ImportXmlToJson.Models.Imports>

@{
    ViewData["Title"] = "Title";
}

<body>
    <h1>Работа с договорами</h1>

    <a asp-controller="Imports" asp-action="JsonSerialization">Выгрузить все данные в Json формат</a>

    <form asp-controller="Imports" asp-action="JsonSerializationByStage" style="margin-top: 15px;">
        <input name="stage" />
        <button type="submit" class="btn btn-primary" >Выгрузить данные по указанному Этапу</button>
    </form>

    <table class="table">
        <thead>
            <th>
                @Html.DisplayNameFor( x => x.Contract_Stage)
            </th>
            <th>
                @Html.DisplayNameFor( x => x.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor( x => x.EndDate)
            </th>
        </thead>
        <tbody>
            @foreach (Imports entity in Model)
            {
                <th>
                    @entity.Contract_Stage
                </th>
                <th>
                    @entity.StartDate
                </th>
                <th>
                    @entity.EndDate
                </th>
            }
        </tbody>
    </table>
</body>

ImportXmlToJson/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@*ViewData["Title"] -*@ Работа с документацией</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ImportXmlToJson.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Contracts" asp-action="Index">Добро пожаловать на главную страницу!</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contracts" asp-action="Index">Выгрузка в БД</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Imports" asp-action="Index">Договоры</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>